//
// Created by anyMSG on 11/20/19.
//

#ifndef _ANYMSG_BSP_CONFIG_H_
#define _ANYMSG_BSP_CONFIG_H_
#define HS_PORT_TYPE
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef HS_PORT_TYPE

#ifndef G_BSP_CONFIG
#define G_BSP_COFING extern
#endif

#define h_addr h_addr_list[0]

#define DEFAULT_STRING_LENGTH 256
#define DEFAULT_KEY_STRING_LENGTH 128
#define DEFAULT_SOCKET_DOMAIN_STRING_LENGTH DEFAULT_KEY_STRING_LENGTH
#define DEFAULT_SOCKET_PORT_STRING_LENGTH DEFAULT_KEY_STRING_LENGTH
#define DEFAULT_FILE_PATH_STRING_LENGTH DEFAULT_STRING_LENGTH
#define DEFAULT_FILE_NAME_STRING_LENGTH DEFAULT_STRING_LENGTH

#define DEFAULT_SHMCOMMON_KEY_STRING_LENGTH (2 * DEFAULT_KEY_STRING_LENGTH)
#define DEFAULT_MODULE_NAME_STRING_LENGTH 128
#define DEFAULT_MODULE_TARGET_NAME_STRING_LENGTH 128
#define DEFAULT_COMPLIER_STRING_LENGTH DEFAULT_KEY_STRING_LENGTH
#define DEFAULT_LICENSE_STRING_LENGTH DEFAULT_KEY_STRING_LENGTH
#define DEFAULT_AUTHOR_STRING_LENGTH DEFAULT_KEY_STRING_LENGTH
#define DEFAULT_UNIT_BLOCK_MAX_SIZE_IN_BYTE 4096
#define DEFAULT_SOCKET_MTU_IN_BYTE 1470
#define DEFAULT_SOCKET_MTU_COMPACT_IN_BYTE 548
#define DEFAULT_MALLOC_RETRY_MAX 1000

#define X32_USER_TI_DEFAULT_LENGTH 64

#define DEFAULT_LOWSOCKET_PIPES_PER_PEER 2
#define DEFAULT_CID_SERVER 0
#define DEFAULT_CID_BROADCAST 0xFFFFFFFF
#define DEFAULT_CID_RESERVED_0 0xFFFFFFFE
#define DEFAULT_CID_RESERVED_1 0xFFFFFFFD
#define DEFAULT_CID_RESERVED_2 0xFFFFFFFC
#define DEFAULT_CID_RESERVED_3 0xFFFFFFFB
#define DEFAULT_CID_RESERVED_MAX 0xFFFFFFFA
#define DEFAULT_MSG_RETRIES 0
#define DEFAULT_TIME_STRING_LENGTH 24
#define DEFAULT_TIMESTAMP_OUT_SECONDS 24
#define DEFAULT_BACKBONE_MAINTAN_TIME_SECONDS 2
#define DEFAULT_SUBNET_TABLE_CT_MAX 100

#define SW_CONNECTION_NONEBLOCK 1
#define SW_TIMEOUT_CHECK 1
#define SW_CGI_ENABLE 1
#define PERFORMANCE_TEST_ENABLE 1
#define DEFAULT_KVPARSER_MAX_LINE 256
#define DEFAULT_KVPARSER_KV_MAX_BYTE (2 * 128)

#define SHMCOMMON_PRIVATE_POOL_MULTIPLE                                        \
  32 // 20200330 kliazz@shandong for x32 to x64.hashStringSHM_insert() Out of
     // space 128to256
#define SHMCOMMON_PUBLIC_POOL_SIZE_NODES (20 * 1024)
#define SHMCMinTableSize 3
#define SHM_INFO_SHOW_FLLUSH_MAX 10240
  //=======================================================================
  G_BSP_COFING unsigned long int _port_strlen_(const char *str);
  G_BSP_COFING void *_port_memset_(void *dest, int val, unsigned long int len);
//=======================================================================
#undef HS_PORT_TYPE
#else
#error "please do NOT include this file separate"
#endif
#ifdef __cplusplus
}
#endif
#endif // _ANYMSG_BSP_CONFIG_H_
